import { Calendar, ExternalLink, Sparkles } from "lucide-react";

interface ReadmeInfoProps {
  projectName?: string;
}

export default function ReadmeInfo({ projectName }: ReadmeInfoProps) {
  const data = new Date();
  const date = data.toLocaleDateString();

  return (
    <div>
      {/* top right corner */}
      <div className="flex items-center gap-8">
        {/* Generated by ai badge */}
        <div
          className="relative inline-flex items-center px-3 py-1 rounded-full border border-rose-300 shadow-md bg-white/50 backdrop-blur-sm shadow-rose-100"
        >
          <Sparkles className="h-4 w-4 text-rose-500 animate-[pingSlow_2s_infinite]" />
          <span className="ml-2 text-sm bg-gradient-to-r from-rose-600 to-pink-600 bg-clip-text text-transparent">
            AI Generated
          </span>

          {/* Shine effect */}
          <div
            className="absolute top-0 left-0 w-1/2 h-full 
            bg-gradient-to-r from-transparent via-white/40 to-transparent 
            skew-x-[-20deg] animate-[shine_2s_infinite] pointer-events-none"
          ></div>
        </div>

        {/* Calender */}
        <div className="flex items-center gap-2">
          <Calendar className="h-4 w-4 text-rose-500" />
          <p className="text-sm text-gray-600">{date}</p>
        </div>

        {/* Repo Link */}
        <div className="flex items-center gap-2">
          <ExternalLink className="h-4 w-4 text-rose-500" />
          <p className="text-sm text-gray-600">Visit Repository</p>
        </div>

      </div>

      {/* Project Name */}
      {projectName && (
        <div className="mt-4">
          <h1 className="text-2xl lg:text-4xl font-bold ">
            <span className="bg-linear-to-r from-rose-500 to-orange-600 bg-clip-text text-transparent">
              {projectName}
            </span>
          </h1>
        </div>
      )}
    </div>
  );
}
